<?php include_once 'codebase/reflex.php' ?>
<html><head>

   <TITLE>Lorem Ipsum Test Page</TITLE>
   <META NAME="description"  CONTENT="">
   <META NAME="keywords" CONTENT="CMS, file based, flatfile, CKEditor, web frontend, ">
   <META NAME="cms_theme" CONTENT="">
   <META NAME="cms_menu" CONTENT="">
   <META NAME="cms_hide" CONTENT="">
   <META HTTP-EQUIV="Content-Type" CONTENT="text/html; utf-8">
</head><body>
<h1>Editing Test Page</h1>

<pre style="text-align: center;">
<a href='lorem.php?login=admin'>Log in with <span style="color:#e74c3c;">admin</span> and <span style="color:#e74c3c;">changeme</span></a> to try the editor.</pre>

<p>As well as editing text, try selecting a photo or graphic from your file manager (Explorer, My Pictures, etc.) and dropping it onto the page in the place where you want it to be.&nbsp; It will be added to the page as a Pending Upload. You can reposition the image or adjust its properties by double-clicking it. If you decide you don&#39;t want it in your page, just select it and press the Delete key.&nbsp; When you are happy with your composition, press Save and the image will be sent to the server along with the text. No need to upload before saving, which means great flexibility to try various layouts without waiting or wasting upload bandwidth.</p>

<p>You can also drop other kinds of files onto the page if you want to provide them for download. Or, include playable HTML5 (.webm) or YouTube videos directly.</p>

<p>Try selecting an area of a graphic in Photoshop or similar, copying (Ctrl-C) then pasting to the page (Ctrl-V). This really is an amazingly useful feature for writing reports, etc.&nbsp;</p>

<p>Hint: To turn on spellcheck or add words to your browser&#39;s dictionary, use Control-rightclick.&nbsp;</p>

<hr />
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vel lectus venenatis, porta mi a, mattis lorem. Proin consequat metus ex, eget vulputate dolor efficitur et. Nulla id tincidunt mi. Curabitur dapibus porttitor vulputate. Praesent aliquet ultricies luctus. Vivamus lacinia purus non cursus consectetur. Pellentesque tempus ipsum sit amet fringilla imperdiet. Nulla sit amet iaculis elit. Suspendisse commodo neque ut dictum auctor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus suscipit sapien a luctus lobortis. Nam dignissim leo quis augue porttitor, quis semper lorem ullamcorper. Donec semper quam at enim volutpat tincidunt.</p>

<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris a odio lobortis tellus rutrum sodales id vitae arcu. Sed feugiat tellus vel sapien ornare, quis dapibus nisi dignissim. Nulla bibendum, libero eu tincidunt volutpat, mi dui lobortis risus, eu feugiat magna dolor vitae massa. Nam hendrerit finibus eros, ac hendrerit dolor pellentesque at. Integer vitae pulvinar turpis. Praesent ut molestie risus, sit amet viverra augue. Sed pellentesque, nunc nec feugiat luctus, elit lorem convallis diam, nec bibendum sem felis ac tortor. Curabitur sit amet elit lectus. In egestas ligula sit amet justo blandit imperdiet. Proin blandit nibh mi, non mollis est posuere quis. Nam hendrerit elit fringilla malesuada euismod.</p>

<p>Vestibulum eu cursus ex, sed bibendum metus. Nam blandit consequat eleifend. Integer dictum mollis nisi, non commodo sem luctus quis. Vivamus mollis vehicula neque rutrum molestie. Mauris eros metus, semper ac hendrerit id, tempus quis nulla. Curabitur finibus suscipit urna, non tempor magna vulputate hendrerit. Quisque sodales placerat dictum. Etiam pretium rutrum nulla sit amet suscipit. Mauris congue diam nec nibh volutpat, lobortis feugiat lectus suscipit. Donec convallis ac ipsum eget tristique. Praesent at nibh felis. Integer posuere suscipit massa, id luctus sem ullamcorper non. Nunc dignissim dictum fermentum.</p>

<p>Ut ex dolor, volutpat a tincidunt quis, ultrices vitae dui. Phasellus eu viverra tellus. Aliquam maximus dolor tristique, suscipit diam eu, dapibus velit. Donec sed pretium sapien. Integer elementum erat at enim malesuada bibendum sit amet elementum mauris. Ut finibus vestibulum quam lacinia consectetur. Nullam in fringilla tellus.</p>

<p>Nullam ut facilisis ipsum, sed tempus arcu. Vestibulum ultricies nisl dui, quis fringilla mauris sodales in. In feugiat augue at eros interdum facilisis. Donec laoreet nulla sit amet felis viverra, sed volutpat elit dignissim. Mauris eget ante eu leo porta ultricies non a augue. Praesent accumsan nisl nec turpis maximus vulputate. Sed posuere tempus elit, ac volutpat sem fringilla vitae. Donec pulvinar feugiat iaculis. Ut sit amet erat vel turpis lacinia tincidunt ut eu nibh. Integer dictum ac dolor id laoreet. Praesent fringilla leo vel tristique dictum. Aliquam tristique, arcu eget faucibus porta, quam quam ultricies ante, a luctus ipsum ante id eros. Vestibulum interdum nunc id elit posuere, nec mattis mauris dictum.</p>

<p>Proin gravida facilisis enim, sit amet efficitur orci vestibulum sit amet. Duis feugiat nisl ut consequat elementum. Nulla blandit aliquam ligula, ac elementum ex. Duis ultricies ex lacus, nec pellentesque risus fermentum eu. Aenean at dignissim nulla. Maecenas dolor urna, vehicula ut massa et, interdum auctor ipsum. Ut fringilla nibh id sem gravida, porttitor aliquet dui fermentum. Ut suscipit lobortis tellus, accumsan pharetra nunc interdum ut. Curabitur odio velit, imperdiet in condimentum vitae, rhoncus vitae ante. Aliquam posuere pretium leo quis auctor. Sed pellentesque orci mauris, sit amet efficitur metus tincidunt vel. Proin maximus dolor eget tellus malesuada aliquam.</p>

<p>Curabitur magna diam, mattis quis sodales eu, venenatis posuere metus. Praesent ut ex ipsum. Sed eleifend elit vitae eros tincidunt, eu mollis lacus interdum. Vivamus neque quam, sagittis quis orci ut, molestie molestie ex. Quisque tempor nunc sed nisi luctus facilisis. Donec dictum, dolor vitae consequat suscipit, risus eros accumsan diam, a suscipit lorem quam nec elit. Pellentesque a condimentum lacus, ac sollicitudin magna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;</p>

<p>Pellentesque lacinia purus tortor, non luctus massa egestas nec. Fusce vulputate, justo quis commodo tempus, eros tortor condimentum justo, eu dapibus turpis felis sit amet massa. Etiam efficitur vulputate lectus, at ultricies libero posuere at. Donec non ultrices nisi, non facilisis magna. Nulla turpis erat, facilisis sed nulla non, venenatis facilisis dolor. Nam malesuada pharetra risus vitae mattis. Aenean faucibus vulputate mauris, at sagittis dui faucibus at. Fusce vulputate, dui quis vehicula ornare, nibh leo tempor sapien, non egestas odio nisl sed velit. Fusce rhoncus sapien at pellentesque posuere. Curabitur elit nisi, posuere sed urna at, porta hendrerit massa. Pellentesque vulputate tempus arcu sit amet dignissim. Nulla neque diam, fermentum venenatis hendrerit vel, ultricies at nunc. Cras posuere mi lectus, non bibendum eros tempus at. Ut non eros metus. Quisque lorem erat, lacinia tempus feugiat non, interdum laoreet risus.</p>

<p>Quisque sit amet egestas risus. Sed blandit congue magna ac semper. Nullam in magna non lacus posuere auctor vel non libero. Cras malesuada dolor vitae odio ultrices, id vestibulum ex interdum. Nullam finibus erat nec est finibus fermentum. Duis volutpat leo eget quam accumsan cursus ac in libero. Sed eros ante, pharetra a erat a, lacinia efficitur ligula.</p>

<p>Nunc fermentum, tellus sed volutpat pretium, metus justo maximus augue, ut auctor mi quam sit amet quam. Pellentesque nec gravida quam, et sodales nisi. In hac habitasse platea dictumst. Maecenas vel elit eu tellus vestibulum ultricies. Maecenas facilisis, turpis in pharetra condimentum, est metus tempor elit, et vestibulum mauris enim id ligula. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nam fermentum porttitor magna non pulvinar. Donec scelerisque hendrerit tortor, in elementum elit blandit elementum. Praesent mollis, nulla id elementum vulputate, dolor ligula ultrices elit, suscipit pretium libero dui ac sem. Nulla convallis massa vel erat lobortis ornare. Sed vestibulum lectus et consectetur volutpat. Quisque tortor erat, hendrerit vitae interdum sit amet, laoreet a elit. Aliquam erat volutpat.</p>

<p>Duis at nisl risus. Fusce vitae quam in felis vulputate pulvinar non eget odio. Integer sit amet lorem quam. Etiam sollicitudin gravida interdum. In purus lorem, sollicitudin et odio at, dignissim sagittis turpis. Vivamus et pretium leo. Curabitur placerat mauris eu egestas laoreet. Quisque auctor nisl sed libero porttitor imperdiet. Morbi eu justo nibh. Sed aliquet vestibulum posuere. Pellentesque eget urna dignissim, dictum risus vel, vestibulum urna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum ut urna tempor, convallis augue ac, sollicitudin tortor. Fusce a sodales augue, sed dapibus magna. Vivamus eros nulla, ultrices ut turpis eu, hendrerit malesuada diam.</p>

<p>Aenean lacinia accumsan metus sit amet luctus. Nunc sit amet mollis elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Praesent varius semper sem. Phasellus eget tristique elit. Nulla tincidunt est et mauris bibendum ultricies. Duis congue metus vel magna laoreet, nec consequat nisl vestibulum. Aenean vel finibus nunc, non accumsan ipsum. Mauris hendrerit sollicitudin convallis. Nulla accumsan facilisis nibh quis vehicula. In hac habitasse platea dictumst. Donec nec quam mollis, scelerisque eros id, vulputate tortor. Curabitur sollicitudin arcu molestie consectetur condimentum. Suspendisse sapien lacus, euismod vitae dui a, aliquam gravida quam. Morbi tristique vel tellus eget hendrerit.</p>

<p>Nullam dignissim venenatis lobortis. Duis tristique fermentum lorem sed rhoncus. Nulla sed ultrices justo. Praesent facilisis fringilla pellentesque. Vestibulum ultrices eu nunc vitae tincidunt. Pellentesque sit amet dictum tortor. Pellentesque pellentesque sem vel sapien imperdiet pulvinar. Donec tincidunt molestie condimentum. Sed dignissim mi vitae lectus rhoncus lacinia.</p>

<p>Sed lobortis quam ac ligula tincidunt, sit amet condimentum ante hendrerit. Etiam sed purus ipsum. Morbi eu tempus dolor. Cras in metus ultrices, laoreet lorem quis, congue nulla. Mauris lectus velit, luctus sit amet elementum ac, viverra a leo. Praesent lacinia vel sem id accumsan. Aliquam erat volutpat. Nullam auctor tellus sed leo tempor viverra. Nulla at metus purus. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>

<p>Nam dapibus sodales sodales. Nulla sit amet ornare ipsum. Aenean ut nisi bibendum, aliquet dui a, vestibulum nibh. Ut vehicula imperdiet urna, non iaculis est rutrum nec. Suspendisse sit amet neque ut erat dapibus varius. Fusce fringilla dui vitae eros finibus auctor. Pellentesque non massa commodo, blandit erat vel, feugiat nulla. Vestibulum a consectetur elit, eget condimentum leo. Fusce porttitor facilisis lacus non gravida. Vivamus rhoncus id urna id volutpat. In accumsan ac magna et auctor. Quisque pulvinar purus tortor. In eget vulputate ipsum. Etiam mattis laoreet orci vel volutpat. Etiam et molestie quam.</p>

<p>Nunc aliquam sodales nisl, aliquet tempor mauris pretium in. Ut semper aliquet turpis. Vivamus ac euismod nunc. Sed eu lobortis lorem. Nunc molestie, ligula quis gravida ullamcorper, leo massa viverra magna, nec aliquet arcu odio eget erat. Etiam semper ante a metus interdum pharetra. Nam non nisi viverra nisi placerat blandit non ac nisl.</p>

<p>Fusce auctor arcu non sapien consectetur egestas. Sed lacus nisi, maximus eget mauris at, volutpat hendrerit augue. Quisque sit amet ligula eget dolor sagittis elementum. Ut cursus nisi auctor, convallis velit nec, ornare diam. Donec pulvinar non mi eu ultricies. Cras id magna lacinia ligula commodo rhoncus. Proin suscipit, purus at tincidunt fringilla, leo purus lobortis nunc, non pulvinar nisi sem ornare tortor. Praesent tristique lacinia commodo. Nullam vitae bibendum nulla. Cras auctor interdum elit, ac pretium lorem egestas eu. Integer augue lorem, interdum nec turpis eu, pulvinar mattis est. Suspendisse eu lectus eu metus congue cursus sit amet non nisl. Integer sit amet libero lacus. Ut et feugiat arcu. Duis quis turpis ac nunc euismod aliquet in nec urna. Nulla imperdiet, arcu at suscipit viverra, urna risus euismod mauris, hendrerit dignissim dolor neque vel ante.</p>

<p>Sed bibendum vitae ex id facilisis. In quis auctor neque, malesuada tincidunt velit. Morbi condimentum laoreet metus, a ultrices sapien lacinia at. Nam aliquet sem ut venenatis ultricies. Cras mollis lectus vitae sodales suscipit. Praesent vitae feugiat elit, dignissim venenatis massa. Maecenas scelerisque suscipit nibh, non commodo dui vulputate vel. Cras congue auctor purus ac hendrerit. Donec in pretium lorem. Mauris placerat mi commodo finibus elementum. Ut rutrum accumsan massa, blandit venenatis mi fringilla ac. Praesent venenatis enim interdum, efficitur nisi eget, rhoncus odio. Aenean aliquam tempor hendrerit. Proin egestas diam lobortis condimentum dapibus.</p>

<p>Nulla ut elit sit amet elit cursus porta. Integer ornare libero porta nunc semper, sed sollicitudin ligula iaculis. Aenean fermentum tortor eget ipsum ornare, et vehicula ex congue. Phasellus sem erat, elementum ut enim eu, efficitur blandit enim. Curabitur tincidunt facilisis ex sed placerat. Nunc finibus enim eu arcu tempor iaculis. Pellentesque vestibulum pretium metus, id semper risus sollicitudin non. Fusce nec lorem sit amet dolor vestibulum dictum at eu sem. Aliquam ligula velit, tristique sit amet rhoncus ut, tincidunt a lectus. Proin maximus in nisi sit amet porta. Nulla rhoncus iaculis tortor, nec varius nunc porttitor quis.</p>

<p>Nulla volutpat mauris sit amet dui blandit malesuada. Cras a magna sapien. Cras sed enim porta, ullamcorper ex sit amet, scelerisque urna. Fusce ornare libero tortor, sed malesuada risus suscipit tempor. Fusce luctus eget dui ut consectetur. Morbi vitae bibendum est, id dignissim velit. Nulla suscipit, metus sed vulputate elementum, lectus ligula dignissim augue, at sodales odio nibh sit amet turpis. Morbi et eleifend enim. Praesent faucibus laoreet elementum. Mauris massa magna, mollis pulvinar orci consequat, auctor pharetra est. Etiam non lobortis lorem. Curabitur consectetur, orci a gravida aliquet, ante sem consectetur libero, eget fermentum nisi diam at orci. Fusce quis tellus vel dui convallis maximus vitae eget augue. Mauris urna nibh, ullamcorper nec dolor quis, tempor luctus arcu. Donec congue urna sit amet felis lobortis, vel interdum ante dignissim. In eu faucibus nisi, ac ullamcorper purus.</p>

</body></html>