; <?php exit ?> Retain this line to prevent viewing of file in browser.
[site]
salt=9552
shalevel=2
sitename=your_sitename
cookie=your_sitename_session
theme=seven
plugin=plugin
default_extension=php
browser_cache=0
doctype=html
language=en
charset=utf-8
msie=11
[security]
editkey=login
keepalive=120
timeout=0
harvesting_protection=2
allowed_ips=
prohibited_ips=
[menu]
mainmenu=tree.mnu
quicklinkmenu=quicklink.mnu
multiviews=0
sidemenu_autoclose=0
topmenu_timeout=3
[editing]
add_shebang=1
site_editors=
site_editlevel=
sourcecode_editlevel=3
inline_scripts=4
file_restore=3
admin_upload_any=0
autostart=1
[uploading]
smartsize=1280x1024
overwrite=1
align=left
